steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Directory Structure
        run: |
          echo "=== Current Working Directory ==="
          pwd
          echo "=== List All Files ==="
          ls -R

      - name: Run python main.py
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: python main.py
